"use client"

import React, { useState } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FileUpload } from "@/components/file-upload"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import type { AttachmentFile } from "@/lib/file-utils"
import { cn } from "@/lib/utils"

export interface MetadataFields {
  title?: boolean
  authors?: boolean
  journal?: boolean
  publicationDate?: boolean
}

interface FileUploadSectionProps {
  title: string
  subtitle?: string
  onFileAdd: (file: AttachmentFile, metadata?: Record<string, string>) => void
  onFileRemove: (fileId: string) => void
  files: AttachmentFile[]
  showMetadataForm?: boolean
  metadataFields?: MetadataFields
  autoGenerateDescription?: boolean
  className?: string
}

export function FileUploadSection({
  title,
  subtitle,
  onFileAdd,
  onFileRemove,
  files,
  showMetadataForm = false,
  metadataFields,
  autoGenerateDescription = false,
  className,
}: FileUploadSectionProps) {
  const [pendingFile, setPendingFile] = useState<AttachmentFile | null>(null)
  const [metadata, setMetadata] = useState<Record<string, string>>({})
  const [isMetadataDialogOpen, setIsMetadataDialogOpen] = useState(false)

  const handleFileAdd = (file: AttachmentFile) => {
    if (showMetadataForm && metadataFields) {
      setPendingFile(file)
      setMetadata({})
      setIsMetadataDialogOpen(true)
    } else {
      onFileAdd(file, undefined)
    }
  }

  const handleMetadataSubmit = () => {
    if (pendingFile) {
      onFileAdd(pendingFile, metadata)
      setPendingFile(null)
      setMetadata({})
      setIsMetadataDialogOpen(false)
    }
  }

  const handleMetadataCancel = () => {
    setPendingFile(null)
    setMetadata({})
    setIsMetadataDialogOpen(false)
  }

  return (
    <>
      <Card className={cn("hyntelo-elevation-1", className)}>
        <CardHeader>
          <CardTitle className="text-lg font-medium">{title}</CardTitle>
          {subtitle && <p className="text-sm text-muted-foreground mt-1">{subtitle}</p>}
        </CardHeader>
        <CardContent>
          <FileUpload
            attachments={files}
            onAttachmentAdd={handleFileAdd}
            onAttachmentRemove={onFileRemove}
          />
        </CardContent>
      </Card>

      {/* Metadata Form Dialog */}
      {showMetadataForm && (
        <Dialog open={isMetadataDialogOpen} onOpenChange={setIsMetadataDialogOpen}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Inserisci informazioni documento</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 py-4">
              {metadataFields?.title && (
                <div className="space-y-2">
                  <Label htmlFor="metadata-title">Titolo *</Label>
                  <Input
                    id="metadata-title"
                    value={metadata.title || ""}
                    onChange={(e) => setMetadata({ ...metadata, title: e.target.value })}
                    placeholder="Inserisci il titolo del documento"
                  />
                </div>
              )}
              {metadataFields?.authors && (
                <div className="space-y-2">
                  <Label htmlFor="metadata-authors">Autori *</Label>
                  <Input
                    id="metadata-authors"
                    value={metadata.authors || ""}
                    onChange={(e) => setMetadata({ ...metadata, authors: e.target.value })}
                    placeholder="Es: Rossi et al."
                  />
                </div>
              )}
              {metadataFields?.journal && (
                <div className="space-y-2">
                  <Label htmlFor="metadata-journal">Journal</Label>
                  <Input
                    id="metadata-journal"
                    value={metadata.journal || ""}
                    onChange={(e) => setMetadata({ ...metadata, journal: e.target.value })}
                    placeholder="Nome del journal"
                  />
                </div>
              )}
              {metadataFields?.publicationDate && (
                <div className="space-y-2">
                  <Label htmlFor="metadata-date">Data di pubblicazione</Label>
                  <Input
                    id="metadata-date"
                    type="date"
                    value={metadata.publicationDate || ""}
                    onChange={(e) => setMetadata({ ...metadata, publicationDate: e.target.value })}
                  />
                </div>
              )}
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={handleMetadataCancel}>
                Annulla
              </Button>
              <Button
                onClick={handleMetadataSubmit}
                disabled={
                  (metadataFields?.title && !metadata.title) ||
                  (metadataFields?.authors && !metadata.authors)
                }
              >
                Conferma
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </>
  )
}

