"use client"

import React, { useState } from "react"
import { SearchSection, type SearchField, type AiSearchButton } from "./search-section"
import { FileUploadSection, type MetadataFields } from "./file-upload-section"
import { SearchableItemsTable, type TableColumn } from "./searchable-items-table"
import { SearchResultsModal, type ResultColumn } from "./search-results-modal"
import type { AttachmentFile } from "@/lib/file-utils"

export interface SearchConfig<T> {
  enabled: boolean
  title: string
  subtitle?: string
  fields: SearchField[]
  onSearch: (values: Record<string, string>) => Promise<T[]>
  aiSearch?: AiSearchButton
  searchButtonLabel?: string
  resultColumns: ResultColumn<T>[]
}

export interface UploadConfig {
  enabled: boolean
  title: string
  subtitle?: string
  showMetadataForm?: boolean
  metadataFields?: MetadataFields
  autoGenerateDescription?: boolean
}

export interface TableConfig<T> {
  title: string | ((count: number) => string)
  columns: TableColumn<T>[]
  emptyMessage?: string
}

interface ItemsManagerProps<T> {
  searchConfig?: SearchConfig<T>
  uploadConfig?: UploadConfig
  tableConfig: TableConfig<T>
  items: T[]
  onItemsChange: (items: T[]) => void
  getItemId: (item: T) => string
  onFileAdd?: (file: AttachmentFile, metadata?: Record<string, string>) => void
  onFileRemove?: (fileId: string) => void
  files?: AttachmentFile[]
  className?: string
}

export function ItemsManager<T>({
  searchConfig,
  uploadConfig,
  tableConfig,
  items,
  onItemsChange,
  getItemId,
  onFileAdd,
  onFileRemove,
  files = [],
  className,
}: ItemsManagerProps<T>) {
  const [searchResults, setSearchResults] = useState<T[]>([])
  const [isSearchModalOpen, setIsSearchModalOpen] = useState(false)
  const [isSearching, setIsSearching] = useState(false)

  const handleSearch = async (values: Record<string, string>) => {
    if (!searchConfig) return

    setIsSearching(true)
    try {
      const results = await searchConfig.onSearch(values)
      setSearchResults(results)
      setIsSearchModalOpen(true)
    } catch (error) {
      console.error("Search error:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const handleAiSearch = async (mode: "merge" | "replace") => {
    if (!searchConfig?.aiSearch) return

    setIsSearching(true)
    try {
      await searchConfig.aiSearch.onSearch(mode)
      // AI search might directly update items, so we don't need to show modal
      // But if it returns results, we should show them
    } catch (error) {
      console.error("AI search error:", error)
    } finally {
      setIsSearching(false)
    }
  }

  const handleSelectFromSearch = (selectedItems: T[]) => {
    const newItems = [...items, ...selectedItems]
    onItemsChange(newItems)
    setIsSearchModalOpen(false)
    setSearchResults([])
  }

  const handleDelete = (itemId: string) => {
    const newItems = items.filter((item) => getItemId(item) !== itemId)
    onItemsChange(newItems)
  }

  const handleFileAdd = (file: AttachmentFile, metadata?: Record<string, string>) => {
    if (onFileAdd) {
      onFileAdd(file, metadata)
    }
  }

  const handleFileRemove = (fileId: string) => {
    if (onFileRemove) {
      onFileRemove(fileId)
    }
  }

  return (
    <div className={className}>
      <div className="space-y-6">
        {/* Search Section */}
        {searchConfig?.enabled && (
          <SearchSection
            title={searchConfig.title}
            subtitle={searchConfig.subtitle}
            fields={searchConfig.fields}
            onSearch={handleSearch}
            aiSearchButton={
              searchConfig.aiSearch
                ? {
                    ...searchConfig.aiSearch,
                    onSearch: handleAiSearch,
                    loading: isSearching || searchConfig.aiSearch.loading,
                  }
                : undefined
            }
            searchButtonLabel={searchConfig.searchButtonLabel}
          />
        )}

        {/* Upload Section */}
        {uploadConfig?.enabled && (
          <FileUploadSection
            title={uploadConfig.title}
            subtitle={uploadConfig.subtitle}
            onFileAdd={handleFileAdd}
            onFileRemove={handleFileRemove}
            files={files}
            showMetadataForm={uploadConfig.showMetadataForm}
            metadataFields={uploadConfig.metadataFields}
            autoGenerateDescription={uploadConfig.autoGenerateDescription}
          />
        )}

        {/* Table Section */}
        <div className="space-y-2">
          {items.length > 0 && (
            <h3 className="text-lg font-medium">
              {typeof tableConfig.title === "function" ? tableConfig.title(items.length) : tableConfig.title}
            </h3>
          )}
          <SearchableItemsTable
            items={items}
            columns={tableConfig.columns}
            onDelete={handleDelete}
            getItemId={getItemId}
            emptyMessage={tableConfig.emptyMessage}
          />
        </div>
      </div>

      {/* Search Results Modal */}
      {searchConfig?.enabled && (
        <SearchResultsModal
          isOpen={isSearchModalOpen}
          onClose={() => {
            setIsSearchModalOpen(false)
            setSearchResults([])
          }}
          title={`Risultati ricerca (${searchResults.length})`}
          items={searchResults}
          columns={searchConfig.resultColumns}
          onSelect={handleSelectFromSearch}
          getItemId={getItemId}
          multiSelect={true}
        />
      )}
    </div>
  )
}

